library(TraMineR)
data(biofam)
?biofam
head(biofam)
biofam.alphabet <- c("0", "1", "2", "3", "4", "5", "6", "7")
biofam.labels <- c("Parent", "Left", "Married", "Left+Married", "Child", "Left+Child", "Left+Marr+Child", "Divorced")
biofam.scodes <- c("P", "L", "M", "L+M", "C", "L+C", "L+M+C", "D")
biofam.seq <- seqdef(biofam, 10:25, alphabet = biofam.alphabet, states = biofam.scodes, labels = biofam.labels)
seqiplot(biofam.seq)
seqfplot(biofam.seq)
seqdplot(biofam.seq, border=NA)
seqIplot(biofam.seq, sortv = "from.start")
seqIplot(biofam.seq, sortv = "from.end")
print(biofam.seq[1:10, ], format = "SPS")
print(biofam.seq[1:10, ])
